### ISSUE TITLE
Error while using osc api function with cloudkitty

### ISSUE THREAD

**Issue by joek-office** [gtema/openstack#310]
Getting error when using the api function on cloudkitty rest endpoints. When i delete service/group/field, there will be an error message returned, but the rest api will delete the respective resource.

joek@ ~ % osc --os-cloud os-internal --pretty api rating /v1/rating/module_config/hashmap/groups
{
  "groups": [
    {
      "group_id": "a9b097a8-f9ff-4f24-823d-b9cb6e19a4c4",
      "name": "instance_uptime_flavor_id"
    }
  ]
}

joek@ ~ % osc --os-cloud os-internal --pretty api rating "/v1/rating/module_config/hashmap/groups?group_id=a9b097a8-f9ff-4f24-823d-b9cb6e19a4c4" -m delete
failed to serialize data to json: EOF while parsing a value at line 1 column 0
Error: SerializeJson { source: Error("EOF while parsing a value", line: 1, column: 0) }

joek@ ~ % osc --os-cloud os-internal --pretty api rating /v1/rating/module_config/hashmap/groups
{
  "groups": []
}

please instruct me to further investigate the issue.

**Comment by joek-office** [comment]
if i can help in any way, just instruct me.
in the mean time, i will ignore this error.
thank you

**Comment by gtema** [comment]
will be included in next release which I plan for  today later evening.
