### ISSUE TITLE
Missing subnet pool feature

### ISSUE THREAD

**Issue by joek-office** [gtema/openstack#366]
I have to deal with subnet groups but this feature isn't available in the osc client.
How can i access this feature?

in the openstack client it is available through openstack subnet group ...

**Comment by gtema** [comment]
Not implemented as of now. You can still use the API wrapper. I'll try to address this next week

**Comment by gtema** [comment]
@joek-office are you sure "subnet group"? I can't find such resource. There is "subnet pool" or any other possible group except subnet

**Comment by joek-office** [comment]
sorry, i meant subnet pool. yes.

**Comment by gtema** [comment]
subnetpools implementation is now merged and will be included in next release (hopefully tomorrow)

**Comment by gtema** [comment]
released in v0.6.4

**Comment by joek-office** [comment]
Thank you very much.
