### ISSUE TITLE
Add support for network rbac management

### ISSUE THREAD

**Issue by joek-office** [gtema/openstack#423]
Currently there is no support, other than over direct api calls, to manage network rbac rules.
Please add support for this.
https://docs.openstack.org/api-ref/network/v2/#rbac-policies

**Comment by joek-office** [comment]
thank you, works like a charm.
i think you use the api to collect the data from https://docs.openstack.org/api-ref/network/v2/#rbac-policies.
is it possible to print more information in the list command. just the id isn't very informational. 
when this are the information that you get from the api:
```
{
   "rbac_policies": [
      {
         "target_tenant": "*",
         "tenant_id": "3de27ce0a2a54cc6ae06dc62dd0ec832",
         "object_type": "network",
         "object_id": "1f32f072-4d17-4811-b619-3623d018bd40",
         "action": "access_as_external",
         "project_id": "3de27ce0a2a54cc6ae06dc62dd0ec832",
         "id":"6d4c666e-1aad-465e-b670-4d112b760137"
      }
   ]
}
```
can you please export direct also other information like target project, object_type, action in minimal?

**Comment by gtema** [comment]
With '-o wide' you get all columns in the output (you can further fine-tune it with '-f columb_name'). The issue with the default output is that there is certain logic in the Auto-Generation: Id and name are returned always (when present), then there is a list of few common column names that should be there (i.e. description, created_at, ...). It total count of fields is under 6 (if I recall correctly) all fields are returned. In general I can totally understand you comment and I noticed the same in few other places, but the auto-generation have not found good way to deal with it.

**Comment by joek-office** [comment]
ok, thanks for the response.
i think it is not much work all around to set an alias with the option -o wide for the local working environment.
This will fix the problem and is usable as a default.

**Comment by gtema** [comment]
workaround - yes, solution - no. I think it becomes slowly necessary to extend metadata for the auto-generation with optional list of fields to be shown by default. This is not something I will do right now, but soon
