### ISSUE TITLE
list volumes of all tenants broken

### ISSUE THREAD

**Issue by MarRio81** [gtema/openstack#466]
❯ OS_CLOUD=admin@dev2 osc block-storage volume list --all-tenans true --limit=-1
Error:
   0: openstack server error:
      	uri: `https://.........:8776/v3/4ee788627bd142108617079ca329a613/volumes/detail?all_tenans=true&limit=-1`
      	status: `400 Bad Request`
      	data: `{"badRequest":{"code":400,"message":"limit param must be positive"}}`

Location:
   openstack_cli/src/bin/osc.rs:43

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

❯ osc block-storage volume list --all-tenants true
error: unexpected argument '--all-tenants' found

  tip: a similar argument exists: '**--all-tenans**'
 
You introduce a little typo, you miss a **t** in tenants. In the cli options and the api call.

**Comment by gtema** [comment]
Thanks for the report.

This is actually not a typo here, but on the service/codegenerator since complete API bindings are generated from OpenAPI. I will have a look where exactly it is set this way and try to find a solution.
