### ISSUE TITLE
openstack_tui crash on viewing server console data

### ISSUE THREAD

**Issue by joek-office** [gtema/openstack#551]
i will add the auto generated crash report.

- Just for information.
It is not possible to upload toml file type to github. possibly it is better to create another file type or just name the file a different way.
[report-d1e64a7d-b806-409b-8ce9-a40fd701ec1f.txt](https://github.com/user-attachments/files/17040982/report-d1e64a7d-b806-409b-8ce9-a40fd701ec1f.txt)

**Comment by gtema** [comment]
hmm, both issues are interesting.

I see where the crash is happening but I do not really understand why/how. Can you please describe a reproduce:
- switch to servers view
- navigate to any one (or keep the initially selected one)
- press "c"

Please also try to execute:
`osc compute server get-console-output <SERVER_ID>` for the failing server (and place here the sanitized output in json if available)

In my clouds it works, just in some environments there are no logs returned at all. I assume in your cloud this API may return none and not empty output.

wrt report itself - I will have a look. A different library is now being used and I have not gathered experiences with it.

**Comment by joek-office** [comment]
thanks for the fix, will try the new version of tui. 
sorry that i have taken no action in response. too many work to do in the last days.
