### ISSUE TITLE
ostui command line option --all-tenants for Server view

### ISSUE THREAD

**Issue by joek-office** [gtema/openstack#552]
If I show the ostui server view with administrator access rights, it will be handy to show all servers like with the '--all-tenants true' option for os server list.
Otherwise I need for every project a connection entry in my clouds.yaml file.

**Comment by gtema** [comment]
Agreed. I never tried it in admin mode, I just worry that in the context of big cloud this is not what you want to do (or at least possibility to switch to certain project).
Actually on my roadmap is a bit different thing, which does not make --all-tenants necessary, but useful to address your other concern: once you authed you can list all accessible projects. So I want to implement a drop-down for re-auth into accessible domain/project

**Comment by joek-office** [comment]
the solution looks nice and function is given.
thank you for the work.
