### ISSUE TITLE
[SDK] Successfully deleting an image throws error because of empty body

### ISSUE THREAD

**Issue by c-vinet** [gtema/openstack#581]
Hello,
I noticed that when using `query_async` to successfully delete an image, i get the following error:
```
Err(Api { source: OpenStackService { status: 204, uri: http://os-gp.esrf.fr:9292/v2/images/f2d35c73-9443-4581-84cf-417cf38c7d6d?, data: "" } })
```
The status 204 with an empty response is the normal behavior of glance api when an image is deleted, it should not return an error.
See: https://docs.openstack.org/api-ref/image/v2/#delete-image

I tracked down the error to this function in `src/api/rest_endpoint.rs`:
```rust
/// Cast response to Json Value
pub(super) fn get_json<C>(
    rsp: &Response<Bytes>,
    uri: Option<Uri>,
) -> Result<serde_json::Value, ApiError<C::Error>>
where
    C: RestClient,
{
    let status = rsp.status();
    let v = if let Ok(v) = serde_json::from_slice(rsp.body()) {
        v
    } else {
        return Err(ApiError::server_error(uri, status, rsp.body()));
    };
    if !status.is_success() {
        return Err(ApiError::from_openstack(uri, status, v));
    }
    Ok(v)
}
``` 

`serde_json::from_slice` fails when feeded an empty slice, so when the body of the request is empty, it returns an error.
```rust
 serde_json::from_slice(rsp.body()) // This fails when body is empty
```
I did a quick example here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=92c4a0149cab101719215fb1bcfb280e

To fix this issue, we would need to check if the response body is empty before feeding it to `serde_json::from_slice`.

**Comment by c-vinet** [comment]
I used the sdk directly, mainly to automate some instance backups.
I didn't knew about `ignore`, it works fine with it !

Thanks for the help.

**Comment by gtema** [comment]
I added some basic examples to the crate and highlevel doc into the openstack_sdk::api mod
