### ISSUE TITLE
Support for placement and http(s)_proxy?

### ISSUE THREAD

**Issue by goek-han** [gtema/openstack#705]
Hello,

will osc provide support for the placement api? 
I've found this OpenApi spec https://gtema.github.io/openstack-openapi/placement.html but I could not find any commands for it (I would assume them under the compute service). 

And bear with me on this one, but is using a http_proxy possible? With the Python client I remember that installing an extra library is necessary.

**Comment by gtema** [comment]
1) placement OpenAPI is generated, but it only contains urls + methods and doesn't contain bodies. I will get back to that next week
2) I honestly never tried using it with proxy. Will need to check the underlaying libs first

**Comment by gtema** [comment]
proxy works like any usual stuff. You need to set http_proxy/http_proxy env (https://www.golinuxcloud.com/set-up-proxy-http-proxy-environment-variable/), placement support will hopefully come this week

**Comment by gtema** [comment]
Placement commands partially addressed with https://github.com/gtema/openstack/pull/721

**Comment by gtema** [comment]
Placement support is covered in v0.9.0
